### ISSUE TITLE
upload error from mobile

### ISSUE THREAD

**Issue by michael-conway** [DICE-UNC/irods-cloud-browser#119]
see tomcat log, this is from mobile app, doing file upload

```
onse@7f16fca7, irodsAccount=irods://danb@danb-workstation.europa.renci.org:1247]
2015-10-07 15:23:37,511 [http-bio-8080-exec-8] DEBUG connection.IRODSMidLevelProtocol  - calling irods function with byte array
2015-10-07 15:23:37,512 [http-bio-8080-exec-8] DEBUG connection.IRODSMidLevelProtocol  - calling irods function with:<DataObjInp_PI><objPath>/dfc1/home/test1/Screen Shot 2015-10-07 at 10.38.00 AM.png</objPath>
<createMode>33188</createMode>
<openFlags>1</openFlags>
<offset>0</offset>
<dataSize>0</dataSize>
<numThreads>0</numThreads>
<oprType>1</oprType>
<KeyValPair_PI><ssLen>0</ssLen>
</KeyValPair_PI>
</DataObjInp_PI>

2015-10-07 15:23:37,512 [http-bio-8080-exec-8] DEBUG connection.IRODSMidLevelProtocol  - api number is:601
2015-10-07 15:23:37,512 [http-bio-8080-exec-8] DEBUG connection.AbstractIRODSMidLevelProtocol  - functionID: 601
2015-10-07 15:23:37,512 [http-bio-8080-exec-8] DEBUG connection.AbstractIRODSMidLevelProtocol  - header:<MsgHeader_PI><type>RODS_API_REQ</type><msgLen>305</msgLen><errorLen>0</errorLen><bsLen>0</bsLen><intInfo>601</intInfo></MsgHeader_PI>
2015-10-07 15:23:37,512 [http-bio-8080-exec-8] DEBUG connection.AbstractIRODSMidLevelProtocol  - reading message from irods
2015-10-07 15:23:37,512 [http-bio-8080-exec-8] DEBUG connection.AbstractConnection  - IRODSConnection.read, byte array size =  4
2015-10-07 15:23:37,512 [http-bio-8080-exec-8] DEBUG connection.AbstractConnection  - offset = 0
2015-10-07 15:23:37,512 [http-bio-8080-exec-8] DEBUG connection.AbstractConnection  - length = 4
2015-10-07 15:23:37,524 [http-bio-8080-exec-8] DEBUG connection.AbstractConnection  - IRODSConnection.read, byte array size =  146
2015-10-07 15:23:37,524 [http-bio-8080-exec-8] DEBUG connection.AbstractConnection  - offset = 0
2015-10-07 15:23:37,524 [http-bio-8080-exec-8] DEBUG connection.AbstractConnection  - length = 146
2015-10-07 15:23:37,524 [http-bio-8080-exec-8] DEBUG connection.AbstractIRODSMidLevelProtocol  - message length:0
2015-10-07 15:23:37,524 [http-bio-8080-exec-8] DEBUG connection.AbstractIRODSMidLevelProtocol  - error length:140
2015-10-07 15:23:37,524 [http-bio-8080-exec-8] DEBUG connection.AbstractIRODSMidLevelProtocol  - bytesLength:0
2015-10-07 15:23:37,524 [http-bio-8080-exec-8] DEBUG connection.AbstractIRODSMidLevelProtocol  - info value:-24000
2015-10-07 15:23:37,524 [http-bio-8080-exec-8] DEBUG connection.AbstractIRODSMidLevelProtocol  - info is < 0
2015-10-07 15:23:37,524 [http-bio-8080-exec-8] DEBUG connection.AbstractConnection  - IRODSConnection.read, byte array size =  140
2015-10-07 15:23:37,524 [http-bio-8080-exec-8] DEBUG connection.AbstractConnection  - offset = 0
2015-10-07 15:23:37,524 [http-bio-8080-exec-8] DEBUG connection.AbstractConnection  - length = 140
2015-10-07 15:23:37,524 [http-bio-8080-exec-8] ERROR connection.AbstractIRODSMidLevelProtocol  - IRODS error occured msg : -24000
2015-10-07 15:23:37,524 [http-bio-8080-exec-8] DEBUG connection.IRODSErrorScanner  - inspectAndThrowIfNeeded:-24000
2015-10-07 15:23:37,524 [http-bio-8080-exec-8] DEBUG connection.IRODSErrorScanner  - scanning for info value...
2015-10-07 15:23:37,524 [http-bio-8080-exec-8] DEBUG connection.IRODSErrorScanner  - errorEnum val:SYS_INTERNAL_NULL_INPUT_ERR
2015-10-07 15:23:37,527 [http-bio-8080-exec-8] ERROR controllers.FileController  - exception in upload transfer
org.irods.jargon.core.exception.JargonException: error code received from iRODS:-24000 message:collection '/dfc1/home/test1' is unknown
	at org.irods.jargon.core.connection.IRODSErrorScanner.checkSpecificCodesAndThrowIfExceptionLocated(IRODSErrorScanner.java:331)
	at org.irods.jargon.core.connection.IRODSErrorScanner.inspectAndThrowIfNeeded(IRODSErrorScanner.java:123)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.processMessageInfoLessThanZero(AbstractIRODSMidLevelProtocol.java:1172)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.readMessage(AbstractIRODSMidLevelProtocol.java:663)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.readMessage(AbstractIRODSMidLevelProtocol.java:629)
	at org.irods.jargon.core.connection.IRODSMidLevelProtocol.irodsFunction(IRODSMidLevelProtocol.java:231)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.irodsFunction(AbstractIRODSMidLevelProtocol.java:174)
	at org.irods.jargon.core.pub.IRODSFileSystemAOImpl.createFileInResource(IRODSFileSystemAOImpl.java:975)
	at org.irods.jargon.core.pub.IRODSFileSystemAOImpl.createFile(IRODSFileSystemAOImpl.java:869)
	at org.irods.jargon.core.pub.io.IRODSFileImpl.createNewFileCheckNoResourceFound(IRODSFileImpl.java:394)
	at org.irods.jargon.core.pub.io.IRODSFileOutputStream.openIRODSFile(IRODSFileOutputStream.java:124)
	at org.irods.jargon.core.pub.io.IRODSFileOutputStream.<init>(IRODSFileOutputStream.java:92)
	at org.irods.jargon.core.pub.io.IRODSFileFactoryImpl.instanceIRODSFileOutputStream(IRODSFileFactoryImpl.java:237)
	at org.irods.jargon.core.pub.io.IRODSFileFactoryImpl.instanceIRODSFileOutputStream(IRODSFileFactoryImpl.java:205)
	at org.irods.jargon.core.pub.Stream2StreamAOImpl.transferStreamToFileUsingIOStreams(Stream2StreamAOImpl.java:155)
	at org.irods.jargon.idrop.web.controllers.FileController.save(FileController.groovy:162)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at com.brandseye.cors.CorsFilter.doFilter(CorsFilter.java:82)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
2015-10-07 15:23:37,528 [http-bio-8080-exec-8] DEBUG connection.IRODSSession  - closing all irods sessions
2015-10-07 15:23:37,528 [http-bio-8080-exec-8] DEBUG connection.IRODSSession  - found and am closing connection to : irods://danb@danb-workstation.europa.renci.org:1247
2015-10-07 15:23:37,528 [http-bio-8080-exec-8] DEBUG connection.IRODSSimpleProtocolManager  - irodsMidLevelProtocol returned:AbstractIRODSMidLevelProtocol [irodsConnection=irods://danb.tempZone@danb-workstation.europa.renci.org:1247/http-bio-8080-exec-8/1444245817432, irodsProtocolManager=org.irods.jargon.core.connection.IRODSSimpleProtocolManager@2e493d4a, irodsServerProperties=IRODS server properties
    icat enabled?:ICAT_ENABLED
    Server boot time:1439934258
    Rel version:rods4.1.0
    API version:d
    zone:tempZone
    eirods:true
, irodsSession=org.irods.jargon.core.connection.IRODSSession@4a56dd03, startupResponseData=StartupResponseData:
   status:0
   relVersion:rods4.1.0
   apiVersion:d
   reconnPort:20086
   reconnAddr:danb-Workstation
   cookie:389460056, forceSslFlush=false, log=org.slf4j.impl.GrailsLog4jLoggerAdapter(org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol), authResponse=org.irods.jargon.core.connection.auth.AuthResponse@7f16fca7, irodsAccount=irods://danb@danb-workstation.europa.renci.org:1247]
2015-10-07 15:23:37,528 [http-bio-8080-exec-8] DEBUG connection.AbstractIRODSMidLevelProtocol  - shutting down, need to send disconnect to irods
2015-10-07 15:23:37,528 [http-bio-8080-exec-8] DEBUG connection.AbstractIRODSMidLevelProtocol  - sending disconnect message
2015-10-07 15:23:37,528 [http-bio-8080-exec-8] DEBUG connection.AbstractIRODSMidLevelProtocol  - functionID: 0
2015-10-07 15:23:37,528 [http-bio-8080-exec-8] DEBUG connection.AbstractIRODSMidLevelProtocol  - header:<MsgHeader_PI><type>RODS_DISCONNECT</type><msgLen>0</msgLen><errorLen>0</errorLen><bsLen>0</bsLen><intInfo>0</intInfo></MsgHeader_PI>
2015-10-07 15:23:37,529 [http-bio-8080-exec-8] DEBUG connection.AbstractIRODSMidLevelProtocol  - finally, shutdown is being called on the given connection
2015-10-07 15:23:37,529 [http-bio-8080-exec-8] DEBUG connection.IRODSBasicTCPConnection  - shutting down connection: true
2015-10-07 15:23:37,529 [http-bio-8080-exec-8] DEBUG connection.IRODSBasicTCPConnection  - is connected for : irods://danb.tempZone@danb-workstation.europa.renci.org:1247/http-bio-8080-exec-8/1444245817432
2015-10-07 15:23:37,529 [http-bio-8080-exec-8] DEBUG connection.IRODSBasicTCPConnection  - now disconnected
2015-10-07 15:23:37,529 [http-bio-8080-exec-8] DEBUG connection.IRODSSession  - all sessions closed for this Thread
^[[A^[[B^[[B


```

**Comment by matt1123** [comment]
GENERAL:
Remote Address:172.25.8.74:8080
Request URL:http://dfc-test-tomcat1.edc.renci.org:8080/irods-cloud-backend/file
Request Method:POST
Status Code:404 Not Found

RESPONSE HEADERS
Access-Control-Allow-Credentials:true
Access-Control-Allow-Origin:http://localhost:63342
Date:Wed, 07 Oct 2015 19:23:37 GMT
Server:Apache-Coyote/1.1
Transfer-Encoding:chunked

REQUEST HEADERS
Accept:application/json, text/plain, */*
Accept-Encoding:gzip, deflate
Accept-Language:en-US,en;q=0.8,de;q=0.6
Connection:keep-alive
Content-Length:6309
Content-Type:multipart/form-data; boundary=----WebKitFormBoundaryn4cEaspwjaBv25fr
Cookie:JSESSIONID=A0718F72D9E916A1ED15FE9E9DD95619; __utma=11384375.2136419747.1442464502.1442464502.1442464502.1; __utmz=11384375.1442464502.1.1.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not%20provided)
Host:dfc-test-tomcat1.edc.renci.org:8080
Origin:http://localhost:63342
Referer:http://localhost:63342/iRODS-App-8998e48ea68151d2359c8887d95813f87ff6280f/www/index.html
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36

REQUEST PAYLOAD
------WebKitFormBoundaryn4cEaspwjaBv25fr
Content-Disposition: form-data; name="collectionParentName"

/dfc1/home/test1/
------WebKitFormBoundaryn4cEaspwjaBv25fr
Content-Disposition: form-data; name="file"; filename="Screen Shot 2015-10-07 at 10.38.00 AM.png"
Content-Type: image/png


------WebKitFormBoundaryn4cEaspwjaBv25fr--
