### ISSUE TITLE
Metadata Search Does Nothing

### ISSUE THREAD

**Issue by rsplinter** [DICE-UNC/irods-cloud-browser#178]
I have a collection with some metadata. I can run
-bash-4.1$ imeta qu -d RA 'n>' 0
collection: /tempZone/home/randy/Archive
dataObj: Test2.dat
----
collection: /tempZone/home/randy/Archive
dataObj: Test3.dat
----
collection: /tempZone/home/randy/Archive
dataObj: Test4.dat

Obviously the imeta search find the correct file. When I try a similar search using the cloud browser... The search screen returns after having done nothing, apparently. The before and after screen looks like the attached.

![screenshot](https://cloud.githubusercontent.com/assets/17439874/17066134/9d48d56c-5013-11e6-8832-5eccaa8ff8fa.png)

In the logfile I find....

Jul 22 11:43:31 pid:4279 NOTICE: Agent process 4707 exited with status 0
Jul 22 11:46:17 pid:4279 NOTICE: Agent process 4715 started for puser=bandit and cuser=bandit from 192.168.56.30
Jul 22 11:46:18 pid:4715 NOTICE: rsGenQuery: rcGenQuery failed, status = -823000

and

-bash-4.1$ ierror 823000
irods error: -823000 CAT_UNKNOWN_TABLE 

Any ideas would be appreciated. Thanks Gents!!

**Comment by michael-conway** [comment]
we cannot duplicate this here. That looks like a general iRODS error.  Can we get together and re-try this.

**Comment by Pansanel** [comment]
Hi,
I can reproduce this issue on my installation. The iRODS iCAT server is in v3.3.

Here is an extract from the log stack:
`
2017-12-06 10:18:27,806 [http-bio-8080-exec-2] ERROR StackTrace  - Full Stack Trace:
org.irods.jargon.core.exception.NoResourceDefinedException: No resource defined
        at org.irods.jargon.core.connection.IRODSErrorScanner.checkSpecificCodesAndThrowIfExceptionLocated(IRODSErrorScanner.java:182)
        at org.irods.jargon.core.connection.IRODSErrorScanner.inspectAndThrowIfNeeded(IRODSErrorScanner.java:123)
        at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.processMessageInfoLessThanZero(AbstractIRODSMidLevelProtocol.java:1232)
        at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.readMessage(AbstractIRODSMidLevelProtocol.java:724)
        at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.readMessage(AbstractIRODSMidLevelProtocol.java:690)
        at org.irods.jargon.core.connection.IRODSMidLevelProtocol.irodsFunction(IRODSMidLevelProtocol.java:220)
        at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.irodsFunction(AbstractIRODSMidLevelProtocol.java:176)
        at org.irods.jargon.core.pub.IRODSFileSystemAOImpl.createFileInResource(IRODSFileSystemAOImpl.java:977)
        at org.irods.jargon.core.pub.IRODSFileSystemAOImpl.createFile(IRODSFileSystemAOImpl.java:869)
        at org.irods.jargon.core.pub.io.IRODSFileImpl.createNewFileCheckNoResourceFound(IRODSFileImpl.java:394)
        at org.irods.jargon.core.pub.io.IRODSFileOutputStream.openIRODSFile(IRODSFileOutputStream.java:124)
        at org.irods.jargon.core.pub.io.IRODSFileOutputStream.<init>(IRODSFileOutputStream.java:92)
        at org.irods.jargon.core.pub.io.IRODSFileFactoryImpl.instanceIRODSFileOutputStream(IRODSFileFactoryImpl.java:237)
        at org.irods.jargon.vircoll.impl.AbstractVirtualCollectionMaintenanceService.saveJsonStringToFile(AbstractVirtualCollectionMaintenanceService.java:453)
        at org.irods.jargon.vircoll.impl.AbstractVirtualCollectionMaintenanceService.addVirtualCollection(AbstractVirtualCollectionMaintenanceService.java:117)
        at org.irods.jargon.vircoll.impl.AbstractVirtualCollectionMaintenanceService.addOrUpdateVirtualCollection(AbstractVirtualCollectionMaintenanceService.java:664)
        at org.irods.jargon.vircoll.impl.TemporaryQueryServiceImpl.addOrUpdateTemporaryQuery(TemporaryQueryServiceImpl.java:161)
        at org.irods.jargon.vircoll.TemporaryQueryService$addOrUpdateTemporaryQuery.call(Unknown Source)
        at org.irods.jargon.idrop.web.services.MetadataQueryService.storeMetadataQuery(MetadataQueryService.groovy:155)
        at org.irods.jargon.idrop.web.services.MetadataQueryService$storeMetadataQuery$0.call(Unknown Source)
        at org.irods.jargon.idrop.web.controllers.MetadataQueryController.save(MetadataQueryController.groovy:86)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.grails.web.servlet.mvc.MixedGrailsControllerHelper.invoke(MixedGrailsControllerHelper.java:154)
        at org.codehaus.groovy.grails.web.servlet.mvc.AbstractGrailsControllerHelper.handleAction(AbstractGrailsControllerHelper.java:375)
        at org.codehaus.groovy.grails.web.servlet.mvc.AbstractGrailsControllerHelper.executeAction(AbstractGrailsControllerHelper.java:252)
        at org.codehaus.groovy.grails.web.servlet.mvc.AbstractGrailsControllerHelper.handleURI(AbstractGrailsControllerHelper.java:205)
        at org.codehaus.groovy.grails.web.servlet.mvc.AbstractGrailsControllerHelper.handleURI(AbstractGrailsControllerHelper.java:126)
        at org.codehaus.groovy.grails.web.servlet.mvc.SimpleGrailsController.handleRequest(SimpleGrailsController.java:72)
        at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:50)
        at org.codehaus.groovy.grails.web.servlet.GrailsDispatcherServlet.doDispatch(GrailsDispatcherServlet.java:347)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:877)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:966)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:868)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:842)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
`
Cheers,
Jerome
